export const TEST_ACTION = "TEST_ACTION";
export const TEST_ACTION_RESPONSE = "TEST_ACTION_RESPONSE";

export const GET_DOCUMENT = "GET_DOCUMENT";
export const GET_DOCUMENT_RESPONSE = "GET_DOCUMENT_RESPONSE";

export const ADD_DOCUMENT = "ADD_DOCUMENT";
export const ADD_DOCUMENT_RESPONSE = "ADD_DOCUMENT_RESPONSE";
