export const TEST_ACTION = "TEST_ACTION";
export const TEST_ACTION_RESPONSE = "TEST_ACTION_RESPONSE";

export const GET_DOCUMENT = "GET_DOCUMENT";
export const GET_DOCUMENT_RESPONSE = "GET_DOCUMENT_RESPONSE";

export const ADD_DOCUMENT = "ADD_DOCUMENT";
export const ADD_DOCUMENT_RESPONSE = "ADD_DOCUMENT_RESPONSE";

export const ADD_ENTRY_TO_DOCUMENT = "ADD_ENTRY_TO_DOCUMENT";
export const ADD_ENTRY_WITH_TOKENIZATION = "ADD_ENTRY_WITH_TOKENIZATION";

export const SAVE_DOCUMENT_REQUEST = "SAVE_DOCUMENT_REQUEST";

export const PRE_SET_ACTIVE_NODE = "PRE_SET_ACTIVE_NODE";
export const SET_ACTIVE_NODE = "SET_ACTIVE_NODE";
export const UPDATE_ENTRY = "UPDATE_ENTRY";

export const ADD_JUNCTION = "ADD_JUNCTION";
export const UPDATE_JUNCTION = "UPDATE_JUNCTION";
export const UPDATE_NEGATION = "UPDATE_NEGATION";