---
swagger: "2.0"
basePath: /v1
info:
  description: This is the client-server API for IG Coder.
  version: 1.0.0
  title: IG Coder API
  contact:
    email: johabog@stud.ntnu.no
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
- name: Users
- name: Projects
- name: Documents
paths:
  /users:
    get:
      tags:
      - Users
      summary: gets data about all users
      description: |
        Get information about all users - Firebase UUID, full name, whether their account is disabled, whether they are a system administrator, what time their account was created and what time their data was last modified.
      operationId: api.users.get_all
      produces:
      - application/json
      parameters: []
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        "204":
          description: No users exist
    post:
      tags:
      - Users
      summary: creates a user
      description: |
        Adds a new user that has been authenticated with Firebase Auth.
      operationId: api.users.post
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: user_data
        description: Data to create a user of
        required: true
        schema:
          $ref: '#/definitions/User_Post_Body'
      responses:
        "201":
          description: User created
        "400":
          description: Bad request. User data invalid.
        "409":
          description: User ID already exists
  /users/{user_id}:
    get:
      tags:
      - Users
      summary: gets data about a user
      description: |
        By passing in a valid user ID, you can get all that user's information - Firebase UUID, full name, whether their account is disabled, whether they are a system administrator, what time their account was created and what time their data was last modified.
      operationId: api.users.get
      produces:
      - application/json
      parameters:
      - name: user_id
        in: path
        description: the user's ID in the SQL database
        required: true
        type: string
        format: uuid
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        "400":
          description: Bad request. User ID invalid.
        "404":
          description: User ID not found
    patch:
      tags:
      - Users
      summary: updates a user
      description: |
        Can be used to update a user's first and last name as well as set their disabled status.
      operationId: api.users.patch
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user_id
        in: path
        description: the user's ID in the SQL database
        required: true
        type: string
        format: uuid
      - in: body
        name: user_data
        description: The new first name, last name and/or disabled status the user should get
        required: true
        schema:
          $ref: '#/definitions/User_Patch_Body'
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. User data invalid.
        "404":
          description: User ID not found
  /projects:
    post:
      tags:
      - Projects
      summary: creates a new project
      description: |
        Creates a new project from the passed in arguments.
      operationId: api.projects.post
      parameters:
      - in: body
        name: project_data
        description: Data to create a project belonging to one user
        required: true
        schema:
          $ref: '#/definitions/Project_Post_Body'
      responses:
        "201":
          description: Project created
          schema:
            $ref: '#/definitions/Project'
        "400":
          description: Bad request. Project data invalid.
  /projects/{project_id}:
    get:
      tags:
      - Projects
      summary: gets data about a project
      description: |
        Get information about a project - name, description, visibility level, what time it was created and what time its data was last modified.
      operationId: api.projects.get
      produces:
      - application/json
      parameters:
      - name: project_id
        in: path
        description: the project's ID in the SQL database
        required: true
        type: integer
        minimum: 0
        format: int32
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Project'
        "400":
          description: Bad request. Project ID invalid.
        "403":
          description: Permission not granted
        "404":
          description: Project ID not found
    patch:
      tags:
      - Projects
      summary: updates a project
      description: |
        Can be used to update a project's name, description and visibility level.
      operationId: api.projects.patch
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: project_id
        in: path
        description: the project's ID in the SQL database
        required: true
        type: integer
        minimum: 0
        format: int32
      - in: body
        name: project_data
        description: The new data the project should get
        required: true
        schema:
          $ref: '#/definitions/Project_Patch_Body'
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. Project data invalid.
        "403":
          description: Permission not granted
        "404":
          description: Project ID not found
    delete:
      tags:
      - Projects
      summary: deletes a project
      description: |
        Deletes a project along with all its documents.
      operationId: api.projects.delete
      produces:
      - application/json
      parameters:
      - name: project_id
        in: path
        description: the project's ID in the SQL database
        required: true
        type: integer
        minimum: 0
        format: int32
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. Project ID invalid.
        "403":
          description: Permission not granted
        "404":
          description: Project ID not found
  /documents:
    post:
      tags:
        - Documents
      summary: creates a new document
      description: |
        Creates a new document from the passed in arguments.
      operationId: api.documents.post
      parameters:
        - in: body
          name: document_data
          description: Data to create a document
          required: true
          schema:
            $ref: '#/definitions/Document_Post_Body'
      responses:
        "201":
          description: Document created
          schema:
            $ref: '#/definitions/Document'
        "400":
          description: Bad request. Document data invalid.
        "403":
          description: Permission not granted
  /documents/{document_id}:
    get:
      tags:
        - Documents
      summary: gets data about a document
      description: |
        Get information about a document - name, description, visibility level, what time it was created and what time its data was last modified.
      operationId: api.documents.get
      produces:
        - application/json
      parameters:
        - name: document_id
          in: path
          description: the document's ID in the SQL database
          required: true
          type: integer
          minimum: 0
          format: int32
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Document'
        "400":
          description: Bad request. Document ID invalid.
        "403":
          description: Permission not granted
        "404":
          description: Document ID not found
    patch:
      tags:
        - Documents
      summary: updates a document
      description: |
        Can be used to update a document's name, description and visibility level.
      operationId: api.documents.patch
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: document_id
          in: path
          description: the document's ID in the SQL database
          required: true
          type: integer
          minimum: 0
          format: int32
        - in: body
          name: document_data
          description: The new data the document should get
          required: true
          schema:
            $ref: '#/definitions/Document_Patch_Body'
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. Document data invalid.
        "403":
          description: Permission not granted
        "404":
          description: Document ID not found
definitions:
  User:
    type: object
    required:
    - user_id
    - foreign_id
    - first_name
    - last_name
    - disabled
    - privileged
    - created_time
    - modified_time
    properties:
      user_id:
        type: integer
        format: int32
        example: 20
        minimum: 0
      foreign_id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      first_name:
        type: string
        example: John
      last_name:
        type: string
        example: Smith
      disabled:
        type: integer
        minimum: 0
        maximum: 1
        example: 0
      privileged:
        type: integer
        minimum: 0
        maximum: 1
        example: 0
      created_time:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
      modified_time:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
  User_Post_Body:
    type: object
    required:
    - first_name
    - foreign_id
    - last_name
    properties:
      foreign_id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      first_name:
        type: string
        example: John
      last_name:
        type: string
        example: Smith
  User_Patch_Body:
    type: object
    properties:
      firstName:
        type: string
        example: John
      lastName:
        type: string
        example: Smith
      disabled:
        type: integer
        minimum: 0
        maximum: 1
        example: 0
  Project:
    type: object
    required:
    - project_id
    - name
    - description
    - visibility_id
    - created_time
    - modified_time
    properties:
      project_id:
        type: integer
        format: int32
        example: 20
        minimum: 0
      name:
        type: string
        example: My Project
      description:
        type: string
        example: This is a project
      visibility_id:
        type: integer
        format: int8
        minimum: 1
        maximum: 3
        example: 2
      created_time:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
      modified_time:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
  Project_Post_Body:
    type: object
    required:
    - name
    - description
    - user_id
    - visibility_id
    properties:
      user_id:
        type: integer
        format: int32
        minimum: 0
        example: 20
      name:
        type: string
        example: My Project
      description:
        type: string
        example: This is a project
      visibility_id:
        type: integer
        format: int8
        minimum: 1
        maximum: 3
        example: 2
  Project_Patch_Body:
    type: object
    properties:
      name:
        type: string
        example: My Project
      description:
        type: string
        example: This is a project
      visibility_id:
        type: integer
        format: int8
        minimum: 1
        maximum: 3
        example: 2
  Document:
    type: object
    required:
    - document_id
    - name
    - description
    - project_id
    - visibility_id
    - forest
    - created_time
    - modified_time
    properties:
      document_id:
        type: integer
        format: int32
        example: 20
        minimum: 0
      name:
        type: string
        example: My Document
      description:
        type: string
        example: This is a document
      project_id:
        type: integer
        format: int32
        example: 20
        minimum: 0
      visibility_id:
        type: integer
        format: int8
        minimum: 1
        maximum: 3
        example: 2
      forest:
        type: array
        items:
          type: object
      created_time:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
      modified_time:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
  Document_Post_Body:
    type: object
    required:
    - name
    - description
    - project_id
    - visibility_id
    properties:
      name:
        type: string
        example: My Document
      description:
        type: string
        example: This is a document
      project_id:
        type: integer
        format: int32
        minimum: 0
        example: 20
      visibility_id:
        type: integer
        format: int8
        minimum: 1
        maximum: 3
        example: 2
  Document_Patch_Body:
    type: object
    properties:
      name:
        type: string
        example: My Document
      description:
        type: string
        example: This is a document
      visibility_id:
        type: integer
        format: int8
        minimum: 1
        maximum: 3
        example: 2